site_name: Projeto IBM - Web Scraping e Extração de Dados usando APIs
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    background: "#1e3a5f"  # Fundo azul escuro
    surface: "#23395b"  # Superfície azul médio      on-primary: "#ffffff"  # Texto branco
    on-accent: "#ffffff"  # Texto branco
    on-background: "#ffffff"  # Texto branco
    on-surface: "#ffffff"  # Texto branco
plugins:
  - search
  - mkdocstrings:
      default_handler: python  

markdown_extensions:
  - admonition
  - toc:
  
      permalink: true